# fly.toml app configuration file generated for btc-analysis on 2025-03-28T00:17:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'btc-analysis'
primary_region = 'atl'

[build]
  [build.args]
    GO_VERSION = '1.24.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  cpus = 2
  cpu_kind = "shared"
  memory = "512"